#!/bin/bash
avrdude -v -patmega328p -cstk500v2 -Pusb -e -Ulock:w:0x3F:m -Uefuse:w:0x05:m -Uhfuse:w:0xDA:m -Ulfuse:w:0xFF:m
avrdude -v -patmega328p -cstk500v2 -Pusb -Uflash:w:ATmegaBOOT_168_atmega328.hex:i -Ulock:w:0x0F:m
